name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: aqjune/swpp:latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: ./configure.sh /llvm-10.0-releaseassert/bin
    - name: make
      run: make
    - name: make test
      run: make test
